# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hewhosurvives/c++/randomProjects/qt/IFSOperationViewer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hewhosurvives/c++/randomProjects/qt/IFSOperationViewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hewhosurvives/c++/randomProjects/qt/IFSOperationViewer/CMakeFiles /home/hewhosurvives/c++/randomProjects/qt/IFSOperationViewer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hewhosurvives/c++/randomProjects/qt/IFSOperationViewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IFSOperationViewer

# Build rule for target.
IFSOperationViewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IFSOperationViewer
.PHONY : IFSOperationViewer

# fast build rule for target.
IFSOperationViewer/fast:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/build
.PHONY : IFSOperationViewer/fast

IFSImageLabel.o: IFSImageLabel.cpp.o
.PHONY : IFSImageLabel.o

# target to build an object file
IFSImageLabel.cpp.o:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/IFSImageLabel.cpp.o
.PHONY : IFSImageLabel.cpp.o

IFSImageLabel.i: IFSImageLabel.cpp.i
.PHONY : IFSImageLabel.i

# target to preprocess a source file
IFSImageLabel.cpp.i:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/IFSImageLabel.cpp.i
.PHONY : IFSImageLabel.cpp.i

IFSImageLabel.s: IFSImageLabel.cpp.s
.PHONY : IFSImageLabel.s

# target to generate assembly for a file
IFSImageLabel.cpp.s:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/IFSImageLabel.cpp.s
.PHONY : IFSImageLabel.cpp.s

IFSOperationViewer.o: IFSOperationViewer.cpp.o
.PHONY : IFSOperationViewer.o

# target to build an object file
IFSOperationViewer.cpp.o:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/IFSOperationViewer.cpp.o
.PHONY : IFSOperationViewer.cpp.o

IFSOperationViewer.i: IFSOperationViewer.cpp.i
.PHONY : IFSOperationViewer.i

# target to preprocess a source file
IFSOperationViewer.cpp.i:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/IFSOperationViewer.cpp.i
.PHONY : IFSOperationViewer.cpp.i

IFSOperationViewer.s: IFSOperationViewer.cpp.s
.PHONY : IFSOperationViewer.s

# target to generate assembly for a file
IFSOperationViewer.cpp.s:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/IFSOperationViewer.cpp.s
.PHONY : IFSOperationViewer.cpp.s

functionDetails.o: functionDetails.cpp.o
.PHONY : functionDetails.o

# target to build an object file
functionDetails.cpp.o:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/functionDetails.cpp.o
.PHONY : functionDetails.cpp.o

functionDetails.i: functionDetails.cpp.i
.PHONY : functionDetails.i

# target to preprocess a source file
functionDetails.cpp.i:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/functionDetails.cpp.i
.PHONY : functionDetails.cpp.i

functionDetails.s: functionDetails.cpp.s
.PHONY : functionDetails.s

# target to generate assembly for a file
functionDetails.cpp.s:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/functionDetails.cpp.s
.PHONY : functionDetails.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/main.cpp.s
.PHONY : main.cpp.s

moc_IFSImageLabel.o: moc_IFSImageLabel.cxx.o
.PHONY : moc_IFSImageLabel.o

# target to build an object file
moc_IFSImageLabel.cxx.o:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_IFSImageLabel.cxx.o
.PHONY : moc_IFSImageLabel.cxx.o

moc_IFSImageLabel.i: moc_IFSImageLabel.cxx.i
.PHONY : moc_IFSImageLabel.i

# target to preprocess a source file
moc_IFSImageLabel.cxx.i:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_IFSImageLabel.cxx.i
.PHONY : moc_IFSImageLabel.cxx.i

moc_IFSImageLabel.s: moc_IFSImageLabel.cxx.s
.PHONY : moc_IFSImageLabel.s

# target to generate assembly for a file
moc_IFSImageLabel.cxx.s:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_IFSImageLabel.cxx.s
.PHONY : moc_IFSImageLabel.cxx.s

moc_IFSOperationViewer.o: moc_IFSOperationViewer.cxx.o
.PHONY : moc_IFSOperationViewer.o

# target to build an object file
moc_IFSOperationViewer.cxx.o:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_IFSOperationViewer.cxx.o
.PHONY : moc_IFSOperationViewer.cxx.o

moc_IFSOperationViewer.i: moc_IFSOperationViewer.cxx.i
.PHONY : moc_IFSOperationViewer.i

# target to preprocess a source file
moc_IFSOperationViewer.cxx.i:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_IFSOperationViewer.cxx.i
.PHONY : moc_IFSOperationViewer.cxx.i

moc_IFSOperationViewer.s: moc_IFSOperationViewer.cxx.s
.PHONY : moc_IFSOperationViewer.s

# target to generate assembly for a file
moc_IFSOperationViewer.cxx.s:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_IFSOperationViewer.cxx.s
.PHONY : moc_IFSOperationViewer.cxx.s

moc_functionDetails.o: moc_functionDetails.cxx.o
.PHONY : moc_functionDetails.o

# target to build an object file
moc_functionDetails.cxx.o:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_functionDetails.cxx.o
.PHONY : moc_functionDetails.cxx.o

moc_functionDetails.i: moc_functionDetails.cxx.i
.PHONY : moc_functionDetails.i

# target to preprocess a source file
moc_functionDetails.cxx.i:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_functionDetails.cxx.i
.PHONY : moc_functionDetails.cxx.i

moc_functionDetails.s: moc_functionDetails.cxx.s
.PHONY : moc_functionDetails.s

# target to generate assembly for a file
moc_functionDetails.cxx.s:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_functionDetails.cxx.s
.PHONY : moc_functionDetails.cxx.s

moc_utilityFunctions.o: moc_utilityFunctions.cxx.o
.PHONY : moc_utilityFunctions.o

# target to build an object file
moc_utilityFunctions.cxx.o:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_utilityFunctions.cxx.o
.PHONY : moc_utilityFunctions.cxx.o

moc_utilityFunctions.i: moc_utilityFunctions.cxx.i
.PHONY : moc_utilityFunctions.i

# target to preprocess a source file
moc_utilityFunctions.cxx.i:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_utilityFunctions.cxx.i
.PHONY : moc_utilityFunctions.cxx.i

moc_utilityFunctions.s: moc_utilityFunctions.cxx.s
.PHONY : moc_utilityFunctions.s

# target to generate assembly for a file
moc_utilityFunctions.cxx.s:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/moc_utilityFunctions.cxx.s
.PHONY : moc_utilityFunctions.cxx.s

utilityFunctions.o: utilityFunctions.cpp.o
.PHONY : utilityFunctions.o

# target to build an object file
utilityFunctions.cpp.o:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/utilityFunctions.cpp.o
.PHONY : utilityFunctions.cpp.o

utilityFunctions.i: utilityFunctions.cpp.i
.PHONY : utilityFunctions.i

# target to preprocess a source file
utilityFunctions.cpp.i:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/utilityFunctions.cpp.i
.PHONY : utilityFunctions.cpp.i

utilityFunctions.s: utilityFunctions.cpp.s
.PHONY : utilityFunctions.s

# target to generate assembly for a file
utilityFunctions.cpp.s:
	$(MAKE) -f CMakeFiles/IFSOperationViewer.dir/build.make CMakeFiles/IFSOperationViewer.dir/utilityFunctions.cpp.s
.PHONY : utilityFunctions.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... IFSOperationViewer"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IFSImageLabel.o"
	@echo "... IFSImageLabel.i"
	@echo "... IFSImageLabel.s"
	@echo "... IFSOperationViewer.o"
	@echo "... IFSOperationViewer.i"
	@echo "... IFSOperationViewer.s"
	@echo "... functionDetails.o"
	@echo "... functionDetails.i"
	@echo "... functionDetails.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... moc_IFSImageLabel.o"
	@echo "... moc_IFSImageLabel.i"
	@echo "... moc_IFSImageLabel.s"
	@echo "... moc_IFSOperationViewer.o"
	@echo "... moc_IFSOperationViewer.i"
	@echo "... moc_IFSOperationViewer.s"
	@echo "... moc_functionDetails.o"
	@echo "... moc_functionDetails.i"
	@echo "... moc_functionDetails.s"
	@echo "... moc_utilityFunctions.o"
	@echo "... moc_utilityFunctions.i"
	@echo "... moc_utilityFunctions.s"
	@echo "... utilityFunctions.o"
	@echo "... utilityFunctions.i"
	@echo "... utilityFunctions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

